# DriftGuard Alert Configuration

# Global Settings
alert_cooldown_hours: 1
max_alerts_per_day: 100
dedup_window_minutes: 30

# Email Channel Configuration
email:
  enabled: true
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_user: ${DRIFTGUARD_EMAIL_USER}
  smtp_password: ${DRIFTGUARD_EMAIL_PASSWORD}
  use_tls: true
  retry_count: 3
  recipients:
    - driftguardalerts@gmail.com  # Default recipient, can be changed
  template_dir: templates/email

# Slack Channel Configuration
slack:
  enabled: false  # Disabled as per user request
